### ISSUE TITLE
Prevent duplicate lineups

### ISSUE THREAD

**Issue by themultiv3rs3** [zamorarr/coach#17]
Is it possible to prevent duplicate lineups? For example, in nba, many of the players can play multiple positions (PG/SG, SF/PF, PF/C). The optimizer produced duplicate lineups even though the players weren't always in the same lineup position.

**Comment by zamorarr** [comment]
hi @algosync, the optimizer should be preventing duplicate lineups. Happy to help though. Can you provide some example code on how you loaded the data built the lineups? This has happened to others before but it was usually because of duplicate rows in the data or having non-sequential `row_ids`.

**Comment by themultiv3rs3** [comment]
My bad. I just realized I loaded my import file twice so all of the rows in my data model were duplicated. I just tried it again and it is producing unique lineups. Thanks for the tip.

**Comment by zamorarr** [comment]
No problem. Glad it worked.
