### ISSUE TITLE
Error in FUN(left) : invalid argument to unary operator

### ISSUE THREAD

**Issue by bluh32** [zamorarr/coach#24]

**Comment by zamorarr** [comment]
hi @bluh32, were you able to fix this?

**Comment by bluh32** [comment]
Yeah, I forget exactly but I needed to shift my dataframe index column one over or something to get it working (or add an index column).  This is a really cool app, appreciate you putting it together.  Love how you can make a custom contest type.

**Comment by zamorarr** [comment]
Ok awesome. Glad you enjoy it. Feel free to let me know of any other issues you have!
