### ISSUE TITLE
RunTime differences NBA and NFL

### ISSUE THREAD

**Issue by chris13337** [zamorarr/coach#25]
Hi, 
thank you for the amazing package you provided us, Coach!

I have one question how long does it normally take for everybody to get 100 NBA Lineups? I was testing an old main slate with 200 players and I am experiencing 2-3 minutes of runtime, compared to NFL with 750 players in the player pool and I need less than one minute to get the results. 
Does somebody know how to solve this or is it always like this? 

I am looking forward to your answers!

Kind regards, 
Christian Schumacher

**Comment by zamorarr** [comment]
hey @chris13337, were you able to address the issue? just curious.

**Comment by chris13337** [comment]
Hi zamorarr, 
It was stupidness on my side, I put together a test file where I copied players below each other and changed the name/id projection and tried to simulate a 200 player slate with this. the problem was, that I didn't change the Team of the "new" players leaving the optimizer with 6 teams and 200 players and a max of 3 players per team. This resulted in a 1.5 MB big model and ridiculous runtime. Not being stupid, and using a real file with 200+ players with more than 6 teams solves the problem. :))

**Comment by zamorarr** [comment]
Ah ok great. Glad it working for you!
