### ISSUE TITLE
NBA Positions

### ISSUE THREAD

**Issue by klr233** [zamorarr/coach#33]
Hi!

I believe for this year, FanDuel has changed its position requirements so that some players can be put in 2 different position slots (ex. PG/SG). This makes the generic NBA FanDuel model unable to properly optimize a lineup. I'm fairly new to R, but I have been trying for weeks to work around this issue by way of adding and changing custom positions constraints, however I have had no success.

Any help or ideas to resolve this issue would be greatly appreciated!

P.S. This model is very useful and works extremely well (besides this small issue) so I just wanted to say thank you!

**Comment by zamorarr** [comment]
Hi @klr233 . Thanks for letting me know. I will fix that. Do you have a recent csv or excel file with the player data from FanDuel this year? That would help me test to make sure that it is working.

**Comment by klr233** [comment]
Sure! Here is one from Tuesday along with the projections themselves.
[NBA 11-30-21.csv](https://github.com/dfs-with-r/coach/files/7645956/NBA.11-30-21.csv)
[NBA_113021_Projections.csv](https://github.com/dfs-with-r/coach/files/7645959/NBA_113021_Projections.csv)

**Comment by zamorarr** [comment]
Hey @klr233 . This issue should be fixed now. Let me know if it doesn't work for you. Please re-install the package with (ex. with `remotes::install_github("dfs-with-r/coach")`) and try it. Thanks.

**Comment by klr233** [comment]
Yes, it works! Thank you.
